import { HitResult, PageResult } from '../data/apiTypes'

export const mockHitsData: Array<HitResult> = [
  {
    created_at: '2022-11-20T18:26:36.000Z',
    title: 'Collapsed FTX owes nearly $3.1B to top creditors',
    url: 'https://www.reuters.com/business/finance/collapsed-ftx-owes-nearly-31-bln-top-50-creditors-2022-11-20/',
    author: 'mfiguiere',
    points: 1,
    story_text: null,
    comment_text: null,
    num_comments: 0,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1668968796,
    _tags: ['story', 'author_mfiguiere', 'story_33683684'],
    objectID: '33683684',
    _highlightResult: {
      title: {
        value: 'Collapsed FTX owes nearly $3.1B to top creditors',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value:
          'https://www.reuters.com/business/finance/collapsed-ftx-owes-nearly-31-bln-top-50-creditors-2022-11-20/',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: { value: 'mfiguiere', matchLevel: 'none', matchedWords: [] },
    },
  },
  {
    created_at: '2022-11-20T18:23:32.000Z',
    title: 'How to See the Amazon Price History of a Product',
    url: 'https://www.howtogeek.com/734836/how-to-see-amazon-price-histories/',
    author: 'evo_9',
    points: 1,
    story_text: null,
    comment_text: null,
    num_comments: 0,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1668968612,
    _tags: ['story', 'author_evo_9', 'story_33683651'],
    objectID: '33683651',
    _highlightResult: {
      title: {
        value: 'How to See the Amazon Price History of a Product',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value:
          'https://www.howtogeek.com/734836/how-to-see-amazon-price-histories/',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: { value: 'evo_9', matchLevel: 'none', matchedWords: [] },
    },
  },
  {
    created_at: '2022-11-20T18:22:41.000Z',
    title: "Moore's Second Law",
    url: 'https://en.wikipedia.org/wiki/Moore%27s_second_law',
    author: 'doener',
    points: 1,
    story_text: null,
    comment_text: null,
    num_comments: 0,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1668968561,
    _tags: ['story', 'author_doener', 'story_33683644'],
    objectID: '33683644',
    _highlightResult: {
      title: {
        value: "Moore's Second Law",
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value: 'https://en.wikipedia.org/wiki/Moore%27s_second_law',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: { value: 'doener', matchLevel: 'none', matchedWords: [] },
    },
  },
  {
    created_at: '2022-11-20T18:22:38.000Z',
    title: 'The clever camera code on rolls of film',
    url: 'https://www.youtube.com/watch?v=imMBwUGjXHs',
    author: 'Tomte',
    points: 1,
    story_text: null,
    comment_text: null,
    num_comments: 0,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1668968558,
    _tags: ['story', 'author_Tomte', 'story_33683642'],
    objectID: '33683642',
    _highlightResult: {
      title: {
        value: 'The clever camera code on rolls of film',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value: 'https://www.youtube.com/watch?v=imMBwUGjXHs',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: { value: 'Tomte', matchLevel: 'none', matchedWords: [] },
    },
  },
  {
    created_at: '2022-11-20T18:21:35.000Z',
    title:
      '“Escape to Freedom” – Animated Video from the Free Software Foundation (FSF)',
    url: 'https://www.fsf.org/blogs/community/help-others-find-free-software-watch-and-share-escape-to-freedom',
    author: 'aabbcc1241',
    points: 1,
    story_text: null,
    comment_text: null,
    num_comments: 0,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1668968495,
    _tags: ['story', 'author_aabbcc1241', 'story_33683629'],
    objectID: '33683629',
    _highlightResult: {
      title: {
        value:
          '“Escape to Freedom” – Animated Video from the Free Software Foundation (FSF)',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value:
          'https://www.fsf.org/blogs/community/help-others-find-free-software-watch-and-share-escape-to-freedom',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: { value: 'aabbcc1241', matchLevel: 'none', matchedWords: [] },
    },
  },
  {
    created_at: '2022-11-20T18:21:15.000Z',
    title: 'A Needle in a Coastal Haystack',
    url: 'https://www.news.ucsb.edu/2022/020757/needle-coastal-haystack',
    author: 'danboarder',
    points: 1,
    story_text: null,
    comment_text: null,
    num_comments: 0,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1668968475,
    _tags: ['story', 'author_danboarder', 'story_33683627'],
    objectID: '33683627',
    _highlightResult: {
      title: {
        value: 'A Needle in a Coastal Haystack',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value: 'https://www.news.ucsb.edu/2022/020757/needle-coastal-haystack',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: { value: 'danboarder', matchLevel: 'none', matchedWords: [] },
    },
  },
  {
    created_at: '2022-11-20T18:18:44.000Z',
    title: 'Dialup – How things worked 40 years ago',
    url: 'https://finger.csokavar.hu',
    author: 'encse',
    points: 1,
    story_text: null,
    comment_text: null,
    num_comments: 1,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1668968324,
    _tags: ['story', 'author_encse', 'story_33683598'],
    objectID: '33683598',
    _highlightResult: {
      title: {
        value: 'Dialup – How things worked 40 years ago',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value: 'https://finger.csokavar.hu',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: { value: 'encse', matchLevel: 'none', matchedWords: [] },
    },
  },
  {
    created_at: '2022-11-20T18:16:17.000Z',
    title: 'Welcome to the First RISC-V Site',
    url: 'http://riscv.jghuff.com/',
    author: 'susam',
    points: 1,
    story_text: null,
    comment_text: null,
    num_comments: 0,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1668968177,
    _tags: ['story', 'author_susam', 'story_33683571'],
    objectID: '33683571',
    _highlightResult: {
      title: {
        value: 'Welcome to the First RISC-V Site',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value: 'http://riscv.jghuff.com/',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: { value: 'susam', matchLevel: 'none', matchedWords: [] },
    },
  },
  {
    created_at: '2022-11-20T18:16:09.000Z',
    title: 'The Tarot Cards of Tech',
    url: 'http://tarotcardsoftech.artefactgroup.com',
    author: 'activatedgeek',
    points: 2,
    story_text: null,
    comment_text: null,
    num_comments: 0,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1668968169,
    _tags: ['story', 'author_activatedgeek', 'story_33683569'],
    objectID: '33683569',
    _highlightResult: {
      title: {
        value: 'The Tarot Cards of Tech',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value: 'http://tarotcardsoftech.artefactgroup.com',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: {
        value: 'activatedgeek',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    created_at: '2022-11-20T18:15:33.000Z',
    title: 'The Geopolitics of Microchips and Semiconductors',
    url: 'https://www.theredlinepodcast.com/post/episode-81-the-geopolitics-of-microchips-and-semiconductors',
    author: 'doener',
    points: 1,
    story_text: null,
    comment_text: null,
    num_comments: 0,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1668968133,
    _tags: ['story', 'author_doener', 'story_33683565'],
    objectID: '33683565',
    _highlightResult: {
      title: {
        value: 'The Geopolitics of Microchips and Semiconductors',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value:
          'https://www.theredlinepodcast.com/post/episode-81-the-geopolitics-of-microchips-and-semiconductors',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: { value: 'doener', matchLevel: 'none', matchedWords: [] },
    },
  },
  {
    created_at: '2022-11-20T18:14:20.000Z',
    title:
      'A Decentralized Protocol for Remunerating the Open-Source Ecosystem [pdf]',
    url: 'https://tea.xyz/tea.white-paper.pdf',
    author: 'saikatsg',
    points: 2,
    story_text: null,
    comment_text: null,
    num_comments: 0,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1668968060,
    _tags: ['story', 'author_saikatsg', 'story_33683548'],
    objectID: '33683548',
    _highlightResult: {
      title: {
        value:
          'A Decentralized Protocol for Remunerating the Open-Source Ecosystem [pdf]',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value: 'https://tea.xyz/tea.white-paper.pdf',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: { value: 'saikatsg', matchLevel: 'none', matchedWords: [] },
    },
  },
  {
    created_at: '2022-11-20T18:12:16.000Z',
    title: 'Show HN: Crew – A sane web anti-framework inspired by werc',
    url: 'http://crew.0xffff.me/',
    author: 'c4pt0r',
    points: 1,
    story_text: null,
    comment_text: null,
    num_comments: 1,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1668967936,
    _tags: ['story', 'author_c4pt0r', 'story_33683516', 'show_hn'],
    objectID: '33683516',
    _highlightResult: {
      title: {
        value: 'Show HN: Crew – A sane web anti-framework inspired by werc',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value: 'http://crew.0xffff.me/',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: { value: 'c4pt0r', matchLevel: 'none', matchedWords: [] },
    },
  },
]

export const mockResponseData: PageResult = {
  hits: mockHitsData,
  nbHits: 2166359,
  page: 0,
  nbPages: 84,
  hitsPerPage: 12,
  exhaustiveNbHits: false,
  exhaustiveTypo: true,
  exhaustive: { nbHits: false, typo: true },
  query: '',
  params:
    'advancedSyntax=true\u0026analytics=true\u0026analyticsTags=backend\u0026hitsPerPage=12\u0026page=0\u0026tags=%28story%2Cpoll%2Cshow_hn%2Cask_hn%2Cfront_page%29',
  processingTimeMS: 3,
  processingTimingsMS: {
    afterFetch: { total: 1 },
    fetch: { scanning: 1, total: 1 },
    total: 3,
  },
}
